#!/bin/bash

if [ -f "/home/pi/BMS-Core/no_watch_dog" ]; then
  exit
fi

res_django=`ps aux | grep "[m]anage" | wc -l`
res_sender=`ps aux | grep "[s]ender" | wc -l`
res_reciever=`ps aux | grep "[r]eciever" | wc -l`
res_homebridge=`ps aux | grep "[h]omebridge" | wc -l`

cmd_django="sudo python3 /home/pi/BMS-Core/bms/manage.py runserver 0.0.0.0:80"
cmd_sender="sudo python /home/pi/BMS-Core/service/sender.py > /dev/null"
cmd_reciever="sudo python /home/pi/BMS-Core/service/receiver.py > /dev/null"
cmd_homebridge="homebridge > /dev/null"

if [ "$res_django" -eq "0" ]; then
    echo "restart django";
    $cmd_django &
fi

if [ "$res_sender" -eq "0" ]; then
    echo "restart sender";
    $cmd_sender &
fi

if [ "$res_reciever" -eq "0" ]; then
    echo "restart reciever";
    $cmd_reciever &
fi

if [ "$res_homebridge" -eq "0" ]; then
    echo "homebrifge restarted";
    $cmd_homebridge &
fi
