#!/bin/bash

# Setup tools
sudo apt install -y vim openssh-server openssh-client

# Setup Netwrok


# Setup Python
sudo apt install -y python3 python3-pip
sudo pip3 install -r ./requirements.txt
sudo pip3 install -r ./requirements.txt

# Setup Homebridge
sudo apt install -y nodejs npm libavahi-compat-libdnssd-dev
sudo npm install -g homebridge
sudo npm install -g homebridge-http-switch
sudo npm install -g homebridge-thermostat
cp homebridge_config.json ~/.homebridge/config.json

# Setup the rest
crontab crontab_file
