# Generated by Django 2.1.5 on 2019-02-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190201_1400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SceneAccessories',
            new_name='command',
        ),
    ]
