# Generated by Django 2.1.5 on 2019-02-01 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190201_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='backend.Scenes'),
        ),
    ]
