# Generated by Django 2.1.5 on 2019-02-03 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190201_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenes',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.AccessoryGroups'),
            preserve_default=False,
        ),
    ]
