# Generated by Django 2.2.1 on 2019-05-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_scenes_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='analogValue',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessories',
            name='isAnalog',
            field=models.BooleanField(default=False),
        ),
    ]
