# Generated by Django 2.2.1 on 2019-05-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190526_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
